// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     concept_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ConceptEvent struct {
	Type ConceptEventType `json:"type"`

	FdkId string `json:"fdkId"`

	Graph string `json:"graph"`

	Timestamp int64 `json:"timestamp"`
}

const ConceptEventAvroCRC64Fingerprint = "\xe2\xeb\x9e\x11\xa4b\x9d\xba"

func NewConceptEvent() ConceptEvent {
	r := ConceptEvent{}
	return r
}

func DeserializeConceptEvent(r io.Reader) (ConceptEvent, error) {
	t := NewConceptEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeConceptEventFromSchema(r io.Reader, schema string) (ConceptEvent, error) {
	t := NewConceptEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeConceptEvent(r ConceptEvent, w io.Writer) error {
	var err error
	err = writeConceptEventType(r.Type, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FdkId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Graph, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Timestamp, w)
	if err != nil {
		return err
	}
	return err
}

func (r ConceptEvent) Serialize(w io.Writer) error {
	return writeConceptEvent(r, w)
}

func (r ConceptEvent) Schema() string {
	return "{\"fields\":[{\"name\":\"type\",\"type\":{\"name\":\"ConceptEventType\",\"symbols\":[\"CONCEPT_HARVESTED\",\"CONCEPT_REASONED\",\"CONCEPT_REMOVED\"],\"type\":\"enum\"}},{\"name\":\"fdkId\",\"type\":\"string\"},{\"name\":\"graph\",\"type\":\"string\"},{\"logicalType\":\"timestamp-millis\",\"name\":\"timestamp\",\"type\":\"long\"}],\"name\":\"no.fdk.concept.ConceptEvent\",\"type\":\"record\"}"
}

func (r ConceptEvent) SchemaName() string {
	return "no.fdk.concept.ConceptEvent"
}

func (_ ConceptEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ConceptEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ConceptEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ConceptEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ConceptEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ConceptEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ConceptEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ ConceptEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ConceptEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := ConceptEventTypeWrapper{Target: &r.Type}

		return w

	case 1:
		w := types.String{Target: &r.FdkId}

		return w

	case 2:
		w := types.String{Target: &r.Graph}

		return w

	case 3:
		w := types.Long{Target: &r.Timestamp}

		return w

	}
	panic("Unknown field index")
}

func (r *ConceptEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ConceptEvent) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ConceptEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ConceptEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ConceptEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ ConceptEvent) Finalize()                        {}

func (_ ConceptEvent) AvroCRC64Fingerprint() []byte {
	return []byte(ConceptEventAvroCRC64Fingerprint)
}

func (r ConceptEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["type"], err = json.Marshal(r.Type)
	if err != nil {
		return nil, err
	}
	output["fdkId"], err = json.Marshal(r.FdkId)
	if err != nil {
		return nil, err
	}
	output["graph"], err = json.Marshal(r.Graph)
	if err != nil {
		return nil, err
	}
	output["timestamp"], err = json.Marshal(r.Timestamp)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ConceptEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["fdkId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FdkId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for fdkId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["graph"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Graph); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for graph")
	}
	val = func() json.RawMessage {
		if v, ok := fields["timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for timestamp")
	}
	return nil
}
