// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     data_service_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type DataServiceEvent struct {
	Type DataServiceEventType `json:"type"`

	FdkId string `json:"fdkId"`

	Graph string `json:"graph"`

	Timestamp int64 `json:"timestamp"`
}

const DataServiceEventAvroCRC64Fingerprint = "\x877\x02\x00\xde\xd3\xf4#"

func NewDataServiceEvent() DataServiceEvent {
	r := DataServiceEvent{}
	return r
}

func DeserializeDataServiceEvent(r io.Reader) (DataServiceEvent, error) {
	t := NewDataServiceEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeDataServiceEventFromSchema(r io.Reader, schema string) (DataServiceEvent, error) {
	t := NewDataServiceEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeDataServiceEvent(r DataServiceEvent, w io.Writer) error {
	var err error
	err = writeDataServiceEventType(r.Type, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FdkId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Graph, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Timestamp, w)
	if err != nil {
		return err
	}
	return err
}

func (r DataServiceEvent) Serialize(w io.Writer) error {
	return writeDataServiceEvent(r, w)
}

func (r DataServiceEvent) Schema() string {
	return "{\"fields\":[{\"name\":\"type\",\"type\":{\"name\":\"DataServiceEventType\",\"symbols\":[\"DATA_SERVICE_HARVESTED\",\"DATA_SERVICE_REASONED\",\"DATA_SERVICE_REMOVED\"],\"type\":\"enum\"}},{\"name\":\"fdkId\",\"type\":\"string\"},{\"name\":\"graph\",\"type\":\"string\"},{\"logicalType\":\"timestamp-millis\",\"name\":\"timestamp\",\"type\":\"long\"}],\"name\":\"no.fdk.dataservice.DataServiceEvent\",\"type\":\"record\"}"
}

func (r DataServiceEvent) SchemaName() string {
	return "no.fdk.dataservice.DataServiceEvent"
}

func (_ DataServiceEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ DataServiceEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ DataServiceEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ DataServiceEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ DataServiceEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ DataServiceEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ DataServiceEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ DataServiceEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *DataServiceEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := DataServiceEventTypeWrapper{Target: &r.Type}

		return w

	case 1:
		w := types.String{Target: &r.FdkId}

		return w

	case 2:
		w := types.String{Target: &r.Graph}

		return w

	case 3:
		w := types.Long{Target: &r.Timestamp}

		return w

	}
	panic("Unknown field index")
}

func (r *DataServiceEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *DataServiceEvent) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ DataServiceEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ DataServiceEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ DataServiceEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ DataServiceEvent) Finalize()                        {}

func (_ DataServiceEvent) AvroCRC64Fingerprint() []byte {
	return []byte(DataServiceEventAvroCRC64Fingerprint)
}

func (r DataServiceEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["type"], err = json.Marshal(r.Type)
	if err != nil {
		return nil, err
	}
	output["fdkId"], err = json.Marshal(r.FdkId)
	if err != nil {
		return nil, err
	}
	output["graph"], err = json.Marshal(r.Graph)
	if err != nil {
		return nil, err
	}
	output["timestamp"], err = json.Marshal(r.Timestamp)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *DataServiceEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["fdkId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FdkId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for fdkId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["graph"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Graph); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for graph")
	}
	val = func() json.RawMessage {
		if v, ok := fields["timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for timestamp")
	}
	return nil
}
