// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     event_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type EventEventType int32

const (
	EventEventTypeEVENT_HARVESTED EventEventType = 0
	EventEventTypeEVENT_REASONED  EventEventType = 1
	EventEventTypeEVENT_REMOVED   EventEventType = 2
)

func (e EventEventType) String() string {
	switch e {
	case EventEventTypeEVENT_HARVESTED:
		return "EVENT_HARVESTED"
	case EventEventTypeEVENT_REASONED:
		return "EVENT_REASONED"
	case EventEventTypeEVENT_REMOVED:
		return "EVENT_REMOVED"
	}
	return "unknown"
}

func writeEventEventType(r EventEventType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewEventEventTypeValue(raw string) (r EventEventType, err error) {
	switch raw {
	case "EVENT_HARVESTED":
		return EventEventTypeEVENT_HARVESTED, nil
	case "EVENT_REASONED":
		return EventEventTypeEVENT_REASONED, nil
	case "EVENT_REMOVED":
		return EventEventTypeEVENT_REMOVED, nil
	}

	return -1, fmt.Errorf("invalid value for EventEventType: '%s'", raw)

}

func (b EventEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *EventEventType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewEventEventTypeValue(stringVal)
	*b = val
	return err
}

type EventEventTypeWrapper struct {
	Target *EventEventType
}

func (b EventEventTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b EventEventTypeWrapper) SetInt(v int32) {
	*(b.Target) = EventEventType(v)
}

func (b EventEventTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b EventEventTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b EventEventTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b EventEventTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b EventEventTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b EventEventTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b EventEventTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b EventEventTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b EventEventTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b EventEventTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b EventEventTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b EventEventTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b EventEventTypeWrapper) Finalize() {}
