// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     infomodel_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type InformationModelEvent struct {
	Type InformationModelEventType `json:"type"`

	FdkId string `json:"fdkId"`

	Graph string `json:"graph"`

	Timestamp int64 `json:"timestamp"`
}

const InformationModelEventAvroCRC64Fingerprint = "\xf6\xff\xa0Va<p\xd5"

func NewInformationModelEvent() InformationModelEvent {
	r := InformationModelEvent{}
	return r
}

func DeserializeInformationModelEvent(r io.Reader) (InformationModelEvent, error) {
	t := NewInformationModelEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeInformationModelEventFromSchema(r io.Reader, schema string) (InformationModelEvent, error) {
	t := NewInformationModelEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeInformationModelEvent(r InformationModelEvent, w io.Writer) error {
	var err error
	err = writeInformationModelEventType(r.Type, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FdkId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Graph, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Timestamp, w)
	if err != nil {
		return err
	}
	return err
}

func (r InformationModelEvent) Serialize(w io.Writer) error {
	return writeInformationModelEvent(r, w)
}

func (r InformationModelEvent) Schema() string {
	return "{\"fields\":[{\"name\":\"type\",\"type\":{\"name\":\"InformationModelEventType\",\"symbols\":[\"INFORMATION_MODEL_HARVESTED\",\"INFORMATION_MODEL_REASONED\",\"INFORMATION_MODEL_REMOVED\"],\"type\":\"enum\"}},{\"name\":\"fdkId\",\"type\":\"string\"},{\"name\":\"graph\",\"type\":\"string\"},{\"logicalType\":\"timestamp-millis\",\"name\":\"timestamp\",\"type\":\"long\"}],\"name\":\"no.fdk.informationmodels.InformationModelEvent\",\"type\":\"record\"}"
}

func (r InformationModelEvent) SchemaName() string {
	return "no.fdk.informationmodels.InformationModelEvent"
}

func (_ InformationModelEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ InformationModelEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ InformationModelEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ InformationModelEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ InformationModelEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ InformationModelEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ InformationModelEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ InformationModelEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *InformationModelEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := InformationModelEventTypeWrapper{Target: &r.Type}

		return w

	case 1:
		w := types.String{Target: &r.FdkId}

		return w

	case 2:
		w := types.String{Target: &r.Graph}

		return w

	case 3:
		w := types.Long{Target: &r.Timestamp}

		return w

	}
	panic("Unknown field index")
}

func (r *InformationModelEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *InformationModelEvent) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ InformationModelEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ InformationModelEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ InformationModelEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ InformationModelEvent) Finalize()                        {}

func (_ InformationModelEvent) AvroCRC64Fingerprint() []byte {
	return []byte(InformationModelEventAvroCRC64Fingerprint)
}

func (r InformationModelEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["type"], err = json.Marshal(r.Type)
	if err != nil {
		return nil, err
	}
	output["fdkId"], err = json.Marshal(r.FdkId)
	if err != nil {
		return nil, err
	}
	output["graph"], err = json.Marshal(r.Graph)
	if err != nil {
		return nil, err
	}
	output["timestamp"], err = json.Marshal(r.Timestamp)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *InformationModelEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["fdkId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FdkId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for fdkId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["graph"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Graph); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for graph")
	}
	val = func() json.RawMessage {
		if v, ok := fields["timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for timestamp")
	}
	return nil
}
