// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     infomodel_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type InformationModelEventType int32

const (
	InformationModelEventTypeINFORMATION_MODEL_HARVESTED InformationModelEventType = 0
	InformationModelEventTypeINFORMATION_MODEL_REASONED  InformationModelEventType = 1
	InformationModelEventTypeINFORMATION_MODEL_REMOVED   InformationModelEventType = 2
)

func (e InformationModelEventType) String() string {
	switch e {
	case InformationModelEventTypeINFORMATION_MODEL_HARVESTED:
		return "INFORMATION_MODEL_HARVESTED"
	case InformationModelEventTypeINFORMATION_MODEL_REASONED:
		return "INFORMATION_MODEL_REASONED"
	case InformationModelEventTypeINFORMATION_MODEL_REMOVED:
		return "INFORMATION_MODEL_REMOVED"
	}
	return "unknown"
}

func writeInformationModelEventType(r InformationModelEventType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewInformationModelEventTypeValue(raw string) (r InformationModelEventType, err error) {
	switch raw {
	case "INFORMATION_MODEL_HARVESTED":
		return InformationModelEventTypeINFORMATION_MODEL_HARVESTED, nil
	case "INFORMATION_MODEL_REASONED":
		return InformationModelEventTypeINFORMATION_MODEL_REASONED, nil
	case "INFORMATION_MODEL_REMOVED":
		return InformationModelEventTypeINFORMATION_MODEL_REMOVED, nil
	}

	return -1, fmt.Errorf("invalid value for InformationModelEventType: '%s'", raw)

}

func (b InformationModelEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *InformationModelEventType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewInformationModelEventTypeValue(stringVal)
	*b = val
	return err
}

type InformationModelEventTypeWrapper struct {
	Target *InformationModelEventType
}

func (b InformationModelEventTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b InformationModelEventTypeWrapper) SetInt(v int32) {
	*(b.Target) = InformationModelEventType(v)
}

func (b InformationModelEventTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b InformationModelEventTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b InformationModelEventTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b InformationModelEventTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b InformationModelEventTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b InformationModelEventTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b InformationModelEventTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b InformationModelEventTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b InformationModelEventTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b InformationModelEventTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b InformationModelEventTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b InformationModelEventTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b InformationModelEventTypeWrapper) Finalize() {}
