// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     service_schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ServiceEventType int32

const (
	ServiceEventTypeSERVICE_HARVESTED ServiceEventType = 0
	ServiceEventTypeSERVICE_REASONED  ServiceEventType = 1
	ServiceEventTypeSERVICE_REMOVED   ServiceEventType = 2
)

func (e ServiceEventType) String() string {
	switch e {
	case ServiceEventTypeSERVICE_HARVESTED:
		return "SERVICE_HARVESTED"
	case ServiceEventTypeSERVICE_REASONED:
		return "SERVICE_REASONED"
	case ServiceEventTypeSERVICE_REMOVED:
		return "SERVICE_REMOVED"
	}
	return "unknown"
}

func writeServiceEventType(r ServiceEventType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewServiceEventTypeValue(raw string) (r ServiceEventType, err error) {
	switch raw {
	case "SERVICE_HARVESTED":
		return ServiceEventTypeSERVICE_HARVESTED, nil
	case "SERVICE_REASONED":
		return ServiceEventTypeSERVICE_REASONED, nil
	case "SERVICE_REMOVED":
		return ServiceEventTypeSERVICE_REMOVED, nil
	}

	return -1, fmt.Errorf("invalid value for ServiceEventType: '%s'", raw)

}

func (b ServiceEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ServiceEventType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewServiceEventTypeValue(stringVal)
	*b = val
	return err
}

type ServiceEventTypeWrapper struct {
	Target *ServiceEventType
}

func (b ServiceEventTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ServiceEventTypeWrapper) SetInt(v int32) {
	*(b.Target) = ServiceEventType(v)
}

func (b ServiceEventTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ServiceEventTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ServiceEventTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ServiceEventTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ServiceEventTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ServiceEventTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ServiceEventTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ServiceEventTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ServiceEventTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ServiceEventTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ServiceEventTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ServiceEventTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ServiceEventTypeWrapper) Finalize() {}
