---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-fdk-resource-service.yaml
  - service-fdk-resource-service.yaml
images:
  - name: fdk-resource-service
    newName: eu.gcr.io/digdir-fdk-infra/fdk-resource-service
    newTag: $(GIT_COMMIT_SHA)

patchesStrategicMerge:
  - env.yaml
